name: Makefile CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-bionic

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: fix git
      run: git config --global url.https://github.com/.insteadOf git://github.com/

    - name: install dependencies
      run: sudo apt-get install -y build-essential git libgmp3-dev libprocps-dev libgtest-dev python-markdown

    - name: dependencies
      run: ./prepare-depends.sh

    - name: build snarky
      run: cd snarky && make -j
